### ISSUE TITLE
if rec['RECORDID'] == subrecordDict['RECORDID']: TypeError: string indices must be integers

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gozoinks/pyfilemaker#3]
```
I'm trying different finds using pyfilemaker where the only difference in
the find is value of the field I'm looking for. But some of them return
results just find and others return the following error:

Traceback (most recent call last):
  File "<pyshell#37>", line 1, in <module>
    record = fm.doFind({u'productid':9310,})
  File "build\bdist.win32\egg\PyFileMaker\FMServer.py", line 315, in doFind
    return self._doAction( '-find' )
  File "build\bdist.win32\egg\PyFileMaker\FMServer.py", line 533, in _doAction
    result = FMResultset.FMResultset( result )
  File "build\bdist.win32\egg\PyFileMaker\FMResultset.py", line 37, in __init__
    self.doParseResultset()
  File "build\bdist.win32\egg\PyFileMaker\FMResultset.py", line 118, in
doParseResultset
    if rec['RECORDID'] == subrecordDict['RECORDID']:
TypeError: string indices must be integers

The commands I'm running are:

record = fm.doFind({u'productid':9792,}) <-- works
record = fm.doFind({u'productid':9310,}) <-- doesn't

Obviously this won't be very useful without the actual xml response but I'd
prefer to email the files to the project leaders rather than post them
publically.
```

Original issue reported on code.google.com by `AndrewOf...@gmail.com` on 9 Sep 2008 at 11:53

**Comment by SnapshotCiTy** [comment]
is this workaround part of the 'official' code now - or should we patch it on each installation (i'm installing using pip)

Does it mean that any layout containing portals would / could return results that would cause errors?

How do you access the list of records that are inside a portal? It seems to only return one value per field / per portal.

I now that's 3 questions in one comment - but any help is appreciated ;-)
